### ISSUE TITLE
Refactor /tests/unit/components/sl-translate-test.js (and likely /addon/components/sl-translate.js)

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-translate#124]
Should not have to passing parameters to this.subject() that contain the text "Binding" just to test the logic trying to test.  This value on the key is happening when Ember binds a parameter to a value via templating syntax but by passing it in it isn't a thorough enough test.

**Comment by erangeles** [comment]
@notmessenger is this still an issue? It appears to be invalid as the postfix requirement of "binding" and its traces has been removed in both the tests and components in https://github.com/softlayer/sl-ember-translate/pull/200

**Comment by notmessenger** [comment]
@erangeles agreed
