### ISSUE TITLE
Ember.EnumberableUtils.map is deprecated, please refactor to use Array.prototype.map

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-translate#130]
https://github.com/softlayer/sl-ember-translate/blob/bbdc781cec0729a4d4396ccaeb88a8401573f579/addon/components/sl-translate.js#L113 and https://github.com/softlayer/sl-ember-translate/blob/b54d33a5ab77fd603ad2f19c136dd33184424341/addon/services/translate.js#L148 may be affected by this

Once Ember 1.13 is used by this addon

**Comment by notmessenger** [comment]
Work this against the `EmberCLI-1.13.6` branch.

**Comment by jonathandavidson** [comment]
Working on this.

**Comment by jonathandavidson** [comment]
@notmessenger - None of the methods being deprecated in https://github.com/machty/ember.js/commit/909441d1b9508c68623d17002f069b10d1463edb are being used in this library and the examples you listed at this time are using arrays and not Ember.Enumerables. I'm thinking this issue can be closed.
