### ISSUE TITLE
Positional parameter support for components now exists in Ember.  Consider refactor of approach of the component usage in this repo

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-translate#131]
https://github.com/emberjs/ember.js/pull/11028

**Comment by notmessenger** [comment]
May not be beneficial as then position has to be adhered to and may not be the usage contact we want to enforce.

**Comment by notmessenger** [comment]
Work this against either the `EmberCLI-1.13.6` branch or `master` if v1.10.0 has been released.

**Comment by azizpunjani** [comment]
Does this give us any advantages over the more explicit version?

**Comment by notmessenger** [comment]
Do not know.  This is part of what needs to be researched.

**Comment by azizpunjani** [comment]
Did research on this. As discussed, we do not see an immediate benefit allowing the use of positional parameters.

**Comment by notmessenger** [comment]
In a recently-observed conversation in the `#dev-ember` Slack channel Robert Jackson said that Glimmer Components will most likely not support positional parameters.
