### ISSUE TITLE
Convert component unit test to integration test

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-translate#165]
tests/unit/components/sl-translate-test.js

Follow guidance at https://github.com/notmessenger/sl-ember-translate/tree/Issue151 and template provided by `ember generate component-test sl-translate`.  (Note that this will be in a new folder so also remove the older one)

`EmberCLI-1.13.6` is the branch in this repo to complete this task against.

**Comment by erangeles** [comment]
@notmessenger taking this.

**Comment by juwara0** [comment]
I have picked this issue up and am working it. erangeles released it to work another issue.
