### ISSUE TITLE
Deprecation warning:  You modified translatedString twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-translate#166]
The `sl-translate` component causes this error.  The `/demo` url demonstrates this.

`EmberCLI-1.13.6` is the branch in this repo to complete this task against.

**Comment by erangeles** [comment]
@notmessenger taking this.

**Comment by notmessenger** [comment]
Possibly related but think is a different issue causing the same error - https://github.com/emberjs/ember.js/issues/11156
