### ISSUE TITLE
Are any of the test helpers from sl-ember-test-helpers in use in this repo?

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-translate#168]
If not, remove the dependency on the repo and modify sl-ember-translate/tests/helpers/start-app.js

**Comment by erangeles** [comment]
@notmessenger "Are any of the test helpers used in this repo?" - I think we have to answer a bigger question, do we condone the widespread usage and enforce these helpers in all the sl ember related repos? If so then we need to open up issues to refactors the testing specifically in sl-ember-components to use those helpers.
